# More documentation about how to customize your build
# can be found here:
# https://docs.fastlane.tools
fastlane_version "1.109.0"

# This value helps us track success metrics for Fastfiles
# we automatically generate. Feel free to remove this line
# once you get things running smoothly!
generated_fastfile_id "363c31ee-0e2b-4d24-9da2-ff110459374b"

default_platform :android

# Fastfile actions accept additional configuration, but
# don't worry, fastlane will prompt you for required
# info which you can add here later
lane :beta do
  # build the release variant
  gradle(task: 'assemble',
  build_type: 'Release')

  # upload to Google Play
  supply(track: 'beta')
  slack(message: 'Hello everyone, Successfully distributed a new beta build')
end

lane :playstore do
   # build the release variant
     gradle(task: 'assemble',
     build_type: 'Release')
     supply
end


lane :upgrade do
    gradle(task: "assemble",
          build_type: 'Release'
          )
    supply(
        track: 'rollout',
        rollout: '1.1'
    )
end

